### ISSUE TITLE
_bin_messages yields data, but later code expects the whole message

### ISSUE THREAD

**Issue by ali1234** [neumond/python-computer-craft#14]
https://github.com/neumond/python-computer-craft/blob/55d3035a38feefb135174630e340fd778f818515/computercraft/server.py#L17-L21

Here, `msg.data` is yielded.

https://github.com/neumond/python-computer-craft/blob/55d3035a38feefb135174630e340fd778f818515/computercraft/server.py#L78-L80

But this code tries to use the yielded value as a `msg`.

This causes an AttributeError to be raised.

**Comment by neumond** [comment]
This was broken during refactoring & experiments, fixed in current main.
