### ISSUE TITLE
Compatibility with Tweaked

### ISSUE THREAD

**Issue by C-Bookie** [neumond/python-computer-craft#2]
Firstly it must be stated that I think this repo is an elegant bit of work.

So it's become a small obsession to try and fix this repos compatibilty with [Tweaked](https://www.curseforge.com/minecraft/mc-mods/cc-tweaked), since continued development of Computer Craft has kinda faded, some lovley people have made a fork to faithfully keep the mod updated to later versions of minecraft, currently 1.14.4. Unfortunatly though this repo dosen't work out of the box with it. If anyone could asssit in helping port this repo to it, that would be appreciated, other wise I'll be reporting my progress in the hopes of official changes being made to the repo to fix compatibility.

So far I've identifed that the http.post() function requiers a second parameter, so I've added an empty string as a second parameter to computercraft/back.lua:70.
the url variable also dosen't contain the port of the server, at the moment I just manually change this after downloading the lua script.

**Comment by C-Bookie** [comment]
heven't been able to work on this for a while but I've resolved the issue.
replacing computercraft/back.lua:70 with:
    local r = http.post(url..'start/'..os.getComputerID()..'/'..args[1]..'/')
and computercraft/back.lua:76 with:
    r = http.post(url..'gettask/'..os.getComputerID()..'/', "")
however I'm not sure if the change to line 76 breaks some functionality.
request.host on computercraft/server.py:198 also dosen't seem to contain the port which seemed to cause some issue, eventually I hard coded it

**Comment by neumond** [comment]
@C-Bookie Yes, first issue is http.post body parameter is not optional. Second cc http sends malformed Host header and that omits port from url.

Thanks for pointing me to Tweaked! That's very nice they made it compatible with mc1.15. I'll definitely spend couple of evenings to tinker with it. Websockets can completely replace current implementation of http request chain.

**Comment by MordorianGuy** [comment]
Is it compatible with CC: Tweaked today?

**Comment by neumond** [comment]
@MordorianGuy 
Yep, it is. I see no point in supporting original CC. Some bugs may appear though.
