### ISSUE TITLE
Cannot execute "py" after using wget http:127.0.0.1:8080/ py

### ISSUE THREAD

**Issue by Ross015** [neumond/python-computer-craft#3]
Whenever I try to run "py" I get the following error:
py:36: attempt to call field 'unserializeJSON' (a nil value)

**Comment by neumond** [comment]
For some reason there's no `unserializeJSON` in `textutils`. I got rid of JSONs in newer versions anyway, need to make a release..

**Comment by Bmorr1123** [comment]
Any update on a new release @neumond ? I'm having the same issue.

**Comment by neumond** [comment]
Hmm.. Just realized you're probably still running original ComputerCraft. It [doesn't have](http://www.computercraft.info/wiki/Textutils_(API)) unserializeJSON method. I could recommend switching to [ComputerCraft:Tweaked](https://www.curseforge.com/minecraft/mc-mods/cc-tweaked), which is polished, optimized and updated version of original ComputerCraft. But I realize that this advice may lead to breaking existing carefully prepared modpacks.
To support original ComputerCraft I need to adjust old way of communication with server as well, via HTTP long polling instead websockets.

I'll spend some time on this today, but can't promise it will be finished soon. Any help is appreciated.

**Comment by Bmorr1123** [comment]
I am using CC: Tweaked within the FTB Revelations modpack. As far as I know there's nothing changed changed from the original CC: Tweaked mod.

**Comment by neumond** [comment]
I've inspected modpack contents, it contains quite old version cc-tweaked-1.12.2-1.84.0.jar, which expectedly doesn't have unserializeJSON. Even if I fix the issue with JSON serialization, I can't guarantee everything will work, but I'll try to test the package against this specific set of versions. By the way, how do you install pycomputercraft, using docker or pip?

**Comment by Bmorr1123** [comment]
I used pip but I also tried Docker afterwards just in case. I have now uninstalled Docker because I don't want to run the web server 2/7.

**Comment by neumond** [comment]
Current main uses custom serialization format. Although I haven't tested everything on older minecraft && CC yet, there must be no issue with `unserializeJSON` anymore.
